export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Testimonial } from "./Testimonial";
export { default as TestimonialWrapper } from "./TestimonialWrapper";
export { default as BlogsWrapper } from "./BlogsWrapper";
export { default as Blog } from "./Blog";
export { default as BookAppointment } from "./BookAppointment";
export { default as BookAppointmentCard } from "./BookAppointmentCard";
export { default as OurWork } from "./OurWork";
